openapi: 3.0.0
info:
  title: Catchmine Project API
  description: 캐치마인드 프로젝트 "Picketch" API
  version: 1.0.0

# 배포시 주소 변경하기
servers:
  - url: http://localhost:8080/api
    description: 개발 서버

components:
  $ref: "./component/index.yaml"

paths:
  allOf:
    - $ref: "./paths/auth.yaml"
    - $ref: "./paths/user.yaml"

tags:
  - name: Auth
    description: 인증 관련 API
  - name: User
    description: 사용자 관련 API
  - name: Friend
    description: 사용자 친구 관련 API
  - name: Ranking
    description: 랭킹 관련 API
  - name: GameRoom
    description: 게임방 관련 API
